### PR TITLE
Bpmn models

### PR DESCRIPTION
**Pull request by LaraAu**
The BPMN files are now linked in the popover with the additional data the link opens the bpmn file itself.

I added the BPMN files and the links.
- [x]  I miss the actual model part of the workflow mix

### CODE REVIEW

**Comment by simonharrer** [comment]
You could use BPMNviz https://github.com/uniba-dsg/BPMNviz similar to the transformer so that we have images of the performance bpmn processes as well.

**Comment by LaraAu** [comment]
Ok so I'll link the pictures instead of the BPMN files.
I just have a problem that three of the bpmn files have an invalid target-namespace of the schemadocument so BPMNviz is not able to transform them to pictures. For the other bpmn files the transformation worked.

The three files are:
- engine_b: arbitraryCyclesPattern2, exclusiveChoicePattern, sequencePattern

**Comment by simonharrer** [comment]
@VincenzoFerme can you help out here as they are your processes?

**Comment by simonharrer** [comment]
The paths to the png files should be part of the json files, and the system should just load them instead of relying on additional logic.

**Comment by simonharrer** [comment]
Regarding the other files, we just ignore them for now.

**Comment by VincenzoFerme** [comment]
Sorry I did not get the previous ping.

Do you need a png version for `engine_b: arbitraryCyclesPattern2, exclusiveChoicePattern, sequencePattern`?

**Comment by LaraAu** [comment]
@simonharrer 
do we need bpmn versions that are valid for BPMNvis or is it enough to have the png file of it?

**Comment by LaraAu** [comment]
@VincenzoFerme 
Yes, can you please upload the png versions of these three files.

**Comment by VincenzoFerme** [comment]
Attached in the order: arbitarycyclespattern2, exclusivechoicepattern, sequence pattern

arbitarycyclespattern2
exclusivechoicepattern
sequencepattern

**Pull request merged**
